config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources  :brands 
  resources  :products
  root 'brands#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	validates :name, presence: true,
					 uniqueness: { case_sensitive: false }
	belongs_to :user
	has_many :products, dependent: :destroy
	before_validation :normalize_name, on: [ :create, :update ]

	protected
    def normalize_name
      self.name = name.downcase.titleize
    end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	validates :user_id, presence: true
	validates :brand_id, presence: true
	validates :price, numericality: { less_than: 100 }
	belongs_to :user
	belongs_to :brand
	before_validation :normalize_name, on: [ :create, :update ]

	protected
    def normalize_name
      self.name = name.downcase.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable
  has_many :brands
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@brands = current_user.brands
  end

  #User can create a brand, form build
  def new
    @brand = current_user.brands.build
  end

  def show
  	@brand = Brand.find(params[:id])
  end

  def edit
  	@brand = Brand.find(params[:id])
  end

  #User can create a brand, actual brand creation
  def create
  	@brand = current_user.brands.build(brand_params)
  	if @brand.valid?
  		@brand.save
  		redirect_to brands_url
  	else
  	   render :new
  	end
  end

  def update
  	@brand = Brand.find(params[:id])
  	if @brand.update(brand_params) 
  		redirect_to brands_url
  	else 
  		render :edit
  	end
  end

  def destroy
  	@brand = Brand.find(params[:id])
  	@brand.destroy
  	redirect_to brands_url
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@products = current_user.products
    @total_value = @products.sum(:price)
  end

  def new
    if current_user.brands.exists?
      @product = current_user.products.build
      @user_brands = current_user.brands
    else
      flash[:alert  ] = "Please create at least a Brand first."
      redirect_to brands_path 
    end
  end

  def show
  end

  def edit
  	@product = current_user.products.find(params[:id])
    @current_brand = @product.brand
    @user_brands = current_user.brands
  end

  def create
  	@product = current_user.products.build(product_params)
  	if @product.valid?
  		@product.save
  		redirect_to products_url
  	else
  	   render :new
  	end
  end

  def update
    @user_brands = current_user.brands
    @product = current_user.products.find(params[:id])
      if @product.update(product_params) 
        redirect_to products_url
      else
        render :edit
      end
  end

  def destroy
  	@product = current_user.products.find(params[:id])
  	@product.destroy
  	redirect_to products_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand_id, :description, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/edit.html.erb
<div class="row">
	<div class="col-md-12 text-center">
		<h1>Edit Brand</h1>

		<%= form_for(@brand) do |f| %>
		<%= render "shared/error_messages_brand" %>

		  <div class="form-signin well center-block text-center">
		    <%= f.label :name, class: "sr-only" %>
		    <%= f.text_field :name, class: "form-control text-center"%>
		  </div>


		  <div class="actions">
		   <%= button_tag(type: "submit", class: "btn btn-warning") do %>
				<span class="glyphicon glyphicon-refresh"></span> Update
			<% end %> 
		  </div>
		<% end %>
	</div>
</div>

app/views/brands/index.html.erb
<div class= "row">
    <div class= "col-md-12 text-center">
      <h1 class="bg-success custom-table-width">All Brands Created</h1>
    </div>
</div>
    <% if @brands.exists? %>
      <%= render 'layouts/brands' %>
    <% else %>
<div class="row">
      <div class="col-md-12 text-center">
        <p class="lead text-muted">You have no Brands added.</p>
      </div>
    <% end %>
</div>
<div class="row">
    <br>
    <div class="col-md-12 text-center">
      <%= link_to '<span class="glyphicon glyphicon-plus"></span> Add New Brand'.html_safe, new_brand_path, 
                  class: "btn btn-success" %>
    </div>
</div>

app/views/brands/new.html.erb
<div class="row">
	<div class="col-md-12 text-center">
		<h1 class="bg-success custom-table-width" >Add new Brand</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= form_for @brand, url: {action: "create"}, html: {class: "form-signin well center-block text-center"} do |f| %>
		<%= render 'shared/error_messages_brand' %>
		<%= f.text_field :name, placeholder: "Brand name", class: "form-control text-center",
						 autofocus: 'autofocus' %>
		    <%= button_tag(type: "submit", class: "btn btn-success") do %>
				<span class="glyphicon glyphicon-plus"></span> Create Brand
			<% end %> 
		<% end %>
    </div>
</div>

app/views/brands/show.html.erb
<h1>Specified Brand</h1>
<h2><%= @brand.name %></h2>

app/views/layouts/_brands.html.erb
<div class="row">
 <div class="col-md-12">
   <table class= "table table-striped table-hover custom-table-width">
      <thead>
        <tr>
          <th>Name</th>
          <th class="column-10"></th>
          <th class="column-10"></th>
        </tr>
      </thead>

      <tbody>
        <% @brands.each do |brand| %>
          <tr>
            <td><%= brand.name %></td>
            <td><%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe,
                    edit_brand_path(brand) %></td>
            <td><%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                    brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!--Menu "logo" -->
    <div class="navbar-header">
      <!--button for mobile view -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#my-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
      </button>
      <%= link_to('Minitest', root_path, class: "navbar-brand")%>
    </div>
    <!--Menu items -->
    <div class="collapse navbar-collapse" id="my-navbar">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to('Brands', brands_path) %></li>
          <li><%= link_to('Products', products_path) %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to('<span class="glyphicon glyphicon-log-out"></span> Logout'.html_safe, destroy_user_session_path, :method => :delete) %>
            </li>
        </ul>
          
      <% else %>
      <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to('<span class="glyphicon glyphicon-log-in"></span> Sign In'.html_safe, new_user_session_path) %>
          </li>
           <li>
            <%= link_to('<span class="glyphicon glyphicon-circle-arrow-up"></span> Sign Up'.html_safe, new_user_registration_path) %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
	<% flash.each do |message_type, message| %>
       <div class="alert alert-info alert-dismissable fade in"><%= message %><button type="button"
    	class="close" data-dismiss="alert">×</button></div>
  	<% end %>

app/views/layouts/_products.html.erb
<div class="row">
  <div class="col-md-12">
   <div class="table-responsive">
      <table class= "table table-striped table-hover custom-table-width-p">
        <thead>
          <tr>
            <th>Name</th>
            <th>Brand</th>
            <th>Description</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr class="text-left">
              <td><%= product.name %></td>
              <td><%= product.brand.name %></td>
              <td><% if product.description.empty? %>
                  <em>No Description</em>
                  <% else %>
                  <%= product.description %>
                  <% end %>
              </td>
              <td>$<%= product.price %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe,
                      edit_product_path(product) %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                      product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
  </div>
</div>
<div class="row">
    <div class="col-md-12">
      <h2 class="bg-info custom-table-width-p">Total Value: $<%= @total_value %></h2>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minitest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application',
                              'https://fonts.googleapis.com/css?family=Hind|Muli" rel="stylesheet',
                               media: 'all', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <!-- Alerts -->
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1 class="bg-success custom-table-width-p">Edit Product</h1>
  </div>
</div>
<!--test new form-->
<div class="row">
  <div class="col-md-12">
    <%= form_for @product, 
        html: {class: "form-signin custom-table-width-p well center-block text-center"} do |f| %>
    <%= render 'shared/error_messages_product' %>                   
    <div class="form-group row">
      <%= f.label :name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control', autofocus: 'autofocus' %>
      </div>
    </div>
    <div class="form-group row">         
      <%= f.label :brand, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
      <%= f.collection_select(:brand_id, current_user.brands.all, :id, :name, {}, {class: "form-control"}) %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :description, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %></td>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :price, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.number_field :price, class: 'form-control', placeholder: "Amount" %>
              <div class="input-group-addon">.00</div>
            </div>
          </div>
      </div>
    </div>
     <%= button_tag(type: "submit", class: "btn btn-warning") do %>
      <span class="glyphicon glyphicon-refresh"></span> Update Product
    <% end %>  
    <% end %> 
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1 class="bg-success custom-table-width-p">All Products</h1>
    <% if @products.exists? %>
      <%= render "layouts/products" %>
    <% else %>
      <p class="lead text-muted">You have no Products added.</p>
    <% end %>
    <%= link_to '<span class="glyphicon glyphicon-plus"></span> Add New Product'.html_safe, new_product_path, 
                  class: "btn btn-success"  %>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1 class="bg-success custom-table-width-p">Add new Product</h1>
  </div>
</div>
<!--test new form-->
<div class="row">
  <div class="col-md-12">
    <%= form_for @product, url: {action: "create"}, 
        html: {class: "form-signin custom-table-width-p well center-block text-center"} do |f| %>
    <%= render 'shared/error_messages_product' %>                   
    <div class="form-group row">
      <%= f.label :name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control', autofocus: 'autofocus' %>
      </div>
    </div>
    <div class="form-group row">         
      <%= f.label :brand, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
      <%= f.collection_select(:brand_id, current_user.brands.all, :id, :name, {}, {class: "form-control"}) %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :description, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %></td>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :price, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.number_field :price, class: 'form-control', placeholder: "Amount" %>
              <div class="input-group-addon">.00</div>
            </div>
          </div>
      </div>
    </div>
     <%= button_tag(type: "submit", class: "btn btn-success") do %>
      <span class="glyphicon glyphicon-plus"></span> Create Product
    <% end %>  
    <% end %> 
  </div>
</div>

app/views/products/show.html.erb
<h1>Specified Product</h1>
<h2><%= @product.name %></h2>

app/views/shared/_error_messages.html.erb
<% if @brand.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@brand.errors.count, "error") %>.
    </div>
    <ul>
    <% @brand.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_brand.html.erb
<% if @brand.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@brand.errors.count, "error") %>.
       <ul class="text-left">
        <% @brand.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages_product.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@product.errors.count, "error") %>.
      <ul class="text-left">
       <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>